#!/usr/bin/env python3
"""pr_create.py — thin `gh pr create` wrapper. Only ever invoked by run.py
after human-gate approval; the --confirmed guard flag is an accident guard
against a stray standalone call skipping the gate, not a security boundary
— anyone who can run this script can also pass --confirmed.
Usage: pr_create.py <target-repo-path> [title] [body] --confirmed

--confirmed MUST come after any title/body positional values, not between
target_repo and title — argparse's positional-matching does not correctly
distribute a later positional chunk across `nargs='?'` slots once an
optional flag has split the argv into more than one chunk (reproducible:
parse_args(['x', '--confirmed', 'a b']) misparses 'a b' as unrecognized,
parse_args(['x', 'a b', '--confirmed']) parses correctly). Callers: put
--confirmed last.
"""
import argparse
import shutil
import subprocess
import sys
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("target_repo")
    # --confirmed is a real argparse flag (not a positional literal) so it
    # can appear before the positional title/body — matches the bash
    # original's `pr_create.sh <target-repo> --confirmed [title] [body]`
    # call shape, which argparse can't parse as a bare positional (any
    # "--..." token is treated as an option, not a positional value).
    parser.add_argument("--confirmed", action="store_true")
    parser.add_argument("title", nargs="?", default="Automated patch via Agentic Light pipeline")
    parser.add_argument("body", nargs="?",
                         default="Generated by Agentic Light pipeline/run.py after the configured gates passed and explicit human approval.")
    args = parser.parse_args()

    if not args.confirmed:
        print("[pr_create] refusing to run: missing --confirmed guard flag (must be invoked by run.py after human gate approval)", file=sys.stderr)
        return 1

    gh = shutil.which("gh")
    if gh is None:
        print("[pr_create] gh CLI not found — install: https://cli.github.com/", file=sys.stderr)
        return 1

    auth = subprocess.run([gh, "auth", "status"], capture_output=True, encoding="utf-8")
    if auth.returncode != 0:
        print("[pr_create] gh CLI not authenticated — run: gh auth login", file=sys.stderr)
        return 1

    proc = subprocess.run(
        [gh, "pr", "create", "--draft", "--title", args.title, "--body", args.body],
        cwd=str(Path(args.target_repo)), encoding="utf-8",
    )
    return proc.returncode


if __name__ == "__main__":
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")
    sys.exit(main())
