#!/usr/bin/env bash
# pr_create.sh — thin `gh pr create` wrapper. Only ever invoked by run.sh
# after human-gate approval; the --confirmed guard flag stops anyone from
# calling this standalone and skipping the gate.
# Usage: pr_create.sh <target-repo-path> --confirmed [title] [body]
set -euo pipefail

TARGET="${1:?usage: pr_create.sh <target-repo-path> --confirmed [title] [body]}"
CONFIRM_FLAG="${2:-}"
TITLE="${3:-Automated patch via Agentic Light pipeline}"
BODY="${4:-Generated by Agentic Light pipeline/run.sh after ESLint + Playwright gates passed and explicit human approval.}"

if [ "$CONFIRM_FLAG" != "--confirmed" ]; then
  echo "[pr_create] refusing to run: missing --confirmed guard flag (must be invoked by run.sh after human gate approval)" >&2
  exit 1
fi

if ! command -v gh >/dev/null 2>&1; then
  echo "[pr_create] gh CLI not found — install: https://cli.github.com/" >&2
  exit 1
fi

if ! gh auth status >/dev/null 2>&1; then
  echo "[pr_create] gh CLI not authenticated — run: gh auth login" >&2
  exit 1
fi

cd "$TARGET"
gh pr create --draft --title "$TITLE" --body "$BODY"
